require('dotenv').config();
const express = require('express');
const cors = require('cors');
const app = express();
const testRoute = require('./routes/ruta');
const infocasaRoute= require('./routes/infocasaRoutes');
const ultracasaRoute= require('./routes/ultracasaRoutes');
const boliviaOnlineRoute= require('./routes/boliviaOnlineRoute');
const boliviaOnlineVentaRoute= require('./routes/boliviaOnlineVentaRoute');
const remaxRoute= require('./routes/remaxRoute');
const infoAntiRoute=require('./routes/infoAntiRoute');
const infoVentaRoute=require('./routes/infoVentaRoute');
const firmaPropiedadesRoute= require('./routes/FirmaPropiedadesRoute');
const firmaAnticreticoRoute= require('./routes/firmaAnticreticoRoute');
const firmaVentaRoute= require('./routes/firmaVentaRoute');
const getMercadoPropInmuebles= require('./routes/mercadoPropVentaRoute');
const getMercadoPropalquilerInmuebles= require('./routes/mercadoPropRoute');
app.use(cors());
app.use('/api/', testRoute);
app.use('/api/infocasa', infocasaRoute);
app.use('/api/ultracasa', ultracasaRoute);
app.use('/api/boliviaOnline', boliviaOnlineRoute);
app.use('/api/boliviaOnlineVenta', boliviaOnlineVentaRoute);
app.use('/api/remax', remaxRoute);
app.use('/api/infocasaAnticretico', infoAntiRoute);
app.use('/api/infocasaVenta', infoVentaRoute);
app.use('/api/firmaPropiedades', firmaPropiedadesRoute);
app.use('/api/firmaAnticretico', firmaAnticreticoRoute);
app.use('/api/firmaVenta', firmaVentaRoute);
app.use('/api/mercadoPropVenta', getMercadoPropInmuebles);
app.use('/api/mercadoProp', getMercadoPropalquilerInmuebles);
app.listen(process.env.PORT, () => console.log (`Server started on port: ${process.env.PORT}`));

